name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: true
      CCACHE_MAXSIZE: 1G
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.0
      - name: Retrieve version
        run: |
          upstream_version=$(curl -s "https://api.github.com/repos/yujincheng08/BiliRoaming/releases/latest" | grep -o '"tag_name": "[^"]*' | cut -d'"' -f4 | sed 's/^v//')
          commit_count=$(curl -s -I "https://api.github.com/repos/yujincheng08/BiliRoaming/commits?per_page=1" | grep -i "Link:" | grep -o '<[^>]*>; rel="last"' | sed 's/.*<\([^>]*\)>; rel="last".*/\1/' | sed 's/.*page=\([0-9]*\).*/\1/')
          version="${upstream_version}.r${commit_count}"
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}
      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/master' ) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo 'Writing sign key'
            echo releaseStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo releaseKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo releaseKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo releaseStoreFile='key.jks' >> gradle.properties
            echo '${{ secrets.SIGNING_KEY }}' | base64 --decode > key.jks
          fi
      - name: Build with Gradle
        run: |
          which cmake
          sudo rm -rf $ANDROID_HOME/cmake
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease assembleDebug
      - name: Sign Android release
        if: success()
        id: sign
        uses: r0adkll/sign-android-release@v1.0.4
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: snapshot
          path: |
              app/build/outputs/apk
              app/build/outputs/mapping
              app/release
              ${{ steps.sign.outputs.signedReleaseFile }}